baseURL = 'https://sfmunoz.com/'
languageCode = 'en-us'
title = 'CMS'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 30

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

#  [[menus.main]]
#    name = 'Posts'
#    pageRef = '/posts'
#    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
