baseURL = 'https://sfmunoz.com/'
languageCode = 'en-us'
title = 'CMS'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 30

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

#  [[menus.main]]
#    name = 'Posts'
#    pageRef = '/posts'
#    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

  [[module.mounts]]
    source = '../content'
    target = 'content'

[outputs]
  home = ['html', 'rss', 'json']
  page = ['html']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss', 'json']
  term = ['html', 'rss']
